= How to Get Exams Info from Intra
:imagesdir: media
ifndef::backend-pdf[]
:toc: auto
:sectnums:
endif::[]

The Smart Sign does it in the following 6 steps:

. connects to Wi-Fi,
. connects to the 42 Intra server,
. asks the server for a temporary access token using the UID and the Secret,
. retreives the temporary access token from the server response,
. asks the server for exam information for a particular campus, a particular cluster, on a particalar date, using the obtained temporary access token,
. retreives the exam information from the server response.

For testing purposes, this process can be recreated on a computer, in Terminal using Curl:

. enter these variables into the Terminal
+
[source,bash]
----
CLIENT_ID=put_your_42_API_app_UID_number_here
SECRET_ID=put_your_42_API_app_Secret_token_here
----

. ask the 42 Intra server for a temporary access token
+
[source,bash]
----
curl -X POST --data "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${SECRET_ID}" https://api.intra.42.fr/oauth/token
----

. copy the access token from the server response and enter it as a variable into the Terminal
+
[source,bash]
----
TKN=put_received_access_token_here
----

. ask the server to send you the information about exams in the cluster C3 and put it into a .json file. 56 is the ID of the 42 Prague campus. Curl does not like square brackets [ ] in its calls, so they need to be escaped with a backslash \.
+
[source,bash]
----
curl -H "Authorization: Bearer $TKN" "https://api.intra.42.fr/v2/campus/56/exams&filter\[location\]=C3" > c3_exams.json
----

If you want to filter the results down to an exact date, as the Smart Sign does, use the following call instead.

[source,bash]
----
curl -H "Authorization: Bearer $TKN" "https://api.intra.42.fr/v2/campus/56/exams?filter\[location\]=C3&range\[begin_at\]=2024-07-12T05:00:00.000Z,2024-07-12T22:00:00.000Z" > c3_exams1.json
----

. this command opens the .json file in the Terminal
+
[source,bash]
----
python -m json.tool < prague_exams.json | grep "begin_at" | tr -d " ," | awk -F '"begin_at":' '{print("["++count"]:", $2)}'
----

== Example of the 42 server Temporary access token response as the smart sign sees it

[source,http]
----
HTTP/2 200
date: Thu, 11 Jul 2024 13:19:37 GMT
content-type: application/json; charset=utf-8
cache-control: no-store
etag: W/"77a2df7a4e20f5f76e6364d36bc76e8a"
pragma: no-cache
set-cookie: _mkra_stck=15e20a8020c702e70007eb1e185a06fb%3A1720703982.2018037; path=/; max-age=10; expires=Thu, 11 Jul 2024 13:19:47 -0000; HttpOnly
status: 200 OK
vary: Origin,Accept-Encoding
x-rack-cors: preflight-hit; no-origin
x-request-id: 3d153728-82b5-48a0-84e7-7c1f1efe598a
x-runtime: 0.076367
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=5%2Bb21KLqrzLETXPtKW2gerMAMrEPjiLAWT6eRUKeyuOVy3b5pvEr6Tc7D%2BMB%2BB4gqUHrTyXWaYy01CmZjQqUGReP7COyDKfBhKpl75Kwd%2FWrMWCVZD%2FkWhvM1iHF0V43hw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 8a191610cec6bc03-FRA
----

[source,json]
----
{"access_token":"03e4cb9b861dad6c49f2267cf97bd18a942507efa7840dc971008d264596cf89","token_type":"bearer","expires_in":6564,"scope":"public","created_at":1720703340,"secret_valid_until":1722585613}
----

== Example of the 42 server exam information response as the smart sign sees it

[source,http]
----
HTTP/1.1 200 OK
Date: Thu, 28 Nov 2024 06:10:13 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Cache-Control: max-age=0, private, must-revalidate
etag: W/"4dc462b36f78c9e055076113bae0d605"
status: 200 OK
vary: Origin,Accept-Encoding
x-application-id: 67990
x-application-name: 42PRAGUEAPI SCREEN
x-application-roles: None
x-content-type-options: nosniff
x-fast: false
x-frame-options: SAMEORIGIN
x-hourly-ratelimit-limit: 1200
x-hourly-ratelimit-remaining: 1199
x-page: 1
x-per-page: 30
x-rack-cors: preflight-hit; no-origin
x-request-id: 1d409b60-b763-4e10-af5a-8fe35593b80d
x-runtime: 0.196901
x-secondly-ratelimit-limit: 2
x-secondly-ratelimit-remaining: 1
x-total: 1
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
Server: cloudflare
CF-RAY: 8e9831883e36b353-PRG
9fa
----

[source,json]
----
[{"id":21213,"ip_range":"10.11.0.0/16,10.12.0.0/16,10.13.0.0/16","begin_at":"2024-11-28T14:00:00.000Z","end_at":"2024-11-28T17:00:00.000Z","location":"C3","max_people":25,"nbr_subscribers":4,"name":"EXAM STUD","created_at":"2024-11-22T08:20:02.386Z","updated_at":"2024-11-27T23:40:57.806Z","campus":{"id":56,"name":"Prague","time_zone":"Europe/Prague","language":{"id":2,"name":"English","identifier":"en","created_at":"2015-04-14T16:07:38.122Z","updated_at":"2024-11-18T11:22:47.733Z"},"users_count":1335,"vogsphere_id":52,"country":"Czech Republic","address":"AFI CITY TOWER Kolbenova 1021/9 Praha 9 - Vysočany","zip":"19000","city":"Prague","website":"https://42prague.com","facebook":"https://www.facebook.com/42Prague","twitter":"","active":true,"public":true,"email_extension":"42prague.com","default_hidden_phone":false},"cursus":[{"id":21,"created_at":"2019-07-29T08:45:17.896Z","name":"42cursus","slug":"42cursus","kind":"main"},{"id":21,"created_at":"2019-07-29T08:45:17.896Z","name":"42cursus","slug":"42cursus","kind":"main"},{"id":21,"created_at":"2019-07-29T08:45:17.896Z","name":"42cursus","slug":"42cursus","kind":"main"},{"id":21,"created_at":"2019-07-29T08:45:17.896Z","name":"42cursus","slug":"42cursus","kind":"main"},{"id":21,"created_at":"2019-07-29T08:45:17.896Z","name":"42cursus","slug":"42cursus","kind":"main"}],"projects":[{"id":1320,"name":"Exam Rank 02","slug":"exam-rank-02","difficulty":0,"parent":null,"children":[],"attachments":[],"created_at":"2019-07-29T09:05:05.890Z","updated_at":"2024-11-25T08:53:45.680Z","exam":true,"git_id":null,"repository":null},{"id":1321,"name":"Exam Rank 03","slug":"exam-rank-03","difficulty":0,"parent":null,"children":[],"attachments":[],"created_at":"2019-07-29T09:05:15.263Z","updated_at":"2024-11-25T08:56:10.466Z","exam":true,"git_id":null,"repository":null},{"id":1322,"name":"Exam Rank 04","slug":"exam-rank-04","difficulty":0,"parent":null,"children":[],"attachments":[],"created_at":"2019-07-29T09:05:24.256Z","updated_at":"2024-11-25T08:56:32.456Z","exam":true,"git_id":null,"repository":null},{"id":1323,"name":"Exam Rank 05","slug":"exam-rank-05","difficulty":0,"parent":null,"children":[],"attachments":[],"created_at":"2019-07-29T09:05:32.360Z","updated_at":"2024-11-25T08:56:53.071Z","exam":true,"git_id":null,"repository":null},{"id":1324,"name":"Exam Rank 06","slug":"exam-rank-06","difficulty":0,"parent":null,"children":[],"attachments":[],"created_at":"2019-07-29T09:05:39.838Z","updated_at":"2024-11-25T08:57:29.269Z","exam":true,"git_id":null,"repository":null}]}]
----
